name: Open MS Paint Interactively
on: [push]

jobs:
  open-paint:
    runs-on: [self-hosted, Windows, X64, PREDATOR]
    steps:
      - name: Launch MS Paint and close after 5 seconds (bypass execution policy)
        shell: cmd
        run: >
          powershell -NoProfile -ExecutionPolicy Bypass -Command "Start-Process mspaint; Start-Sleep -Seconds 5; (Get-Process -Name mspaint -ErrorAction SilentlyContinue) | ForEach-Object { $_.CloseMainWindow() }"
