name: Open MS Paint Interactively
on: [push]

jobs:
  open-paint:
    runs-on: [self-hosted, Windows, X64, PREDATOR]
    steps:
      - name: Launch MS Paint and close after 5 seconds
        run: |
          # Start MS Paint and get its process object
          $paint = Start-Process mspaint -PassThru

          # Wait 5 seconds so you can see Paint
          Start-Sleep -Seconds 5

          # Close Paint
          $paint.CloseMainWindow()
        shell: powershell
