name: Java CI - InventoryAPI Automation (Windows - Predator)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test on Predator
    runs-on: [self-hosted, Windows, PREDATOR]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install -B

      - name: Run tests
        run: mvn test

      - name: Package JAR
        run: mvn package

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: inventoryapi-jar
          path: target/*.jar
